name: Main workflow

on:
  - pull_request
  - push
  - workflow_dispatch

jobs:
  build:
    name: Build

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        ocaml-version:
          - 4.08.1
          - 4.09.1
          - 4.10.1
          - 4.11.1

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - name: Build code
        run: |
          opam pin add rhovec.dev . --no-action
          opam depext rhovec --yes --with-test
          opam install . --deps-only --with-test
          opam exec -- dune build
