name: Main workflow

on:
  - pull_request
  - push
  - workflow_dispatch

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup OCaml
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: 4.10.0

      - name: Build, format, and test
        run: |
          opam install . --deps-only --with-test
          opam exec -- dune build
          opam exec -- dune build @fmt
          opam exec -- dune runtest
