name: Continuous integration

on:
  pull_request:
  push:
  workflow_dispatch:
    inputs:
      name:
        descriont: "Person"
        default: "hello"

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: echo 'hello'
