name: Main workflow

on:
  - pull_request
  - push
  - workflow_dispatch

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup OCaml
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: 4.10.0

      - name: Install dependencies
        run: opam install . --deps-only --with-test

      - name: Build
        run: opam exec -- dune build

      - name: Format code
        run: opam exec -- dune build @fmt

      - name: Test
        run: opam exec -- dune runtest
